version: 2

machine:
  services:
    - docker

jobs:
  build:
    docker:
      - image: rust:1
    steps:
      - setup-docker-engine
      - checkout
      - run: cargo build
      - run: cargo test -- --nocapture

